### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [AlCalzone/ioBroker.philips-tv#13]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/AlCalzone/ioBroker.philips-tv

- [ ] [E104] No common.titleLang found in io-package.json
- [ ] [E114] No adapter are allowed in the repo without admin3 support
- [ ] [E150] No common.connectionType found in io-package.json
- [ ] [E152] No common.dataSource found in io-package.json
- [ ] [E506] Word "Philips TV adapter settings" is not translated to russian in admin/words.js. You can use https://translator.iobroker.in/ for translations
- [ ] [E506] Word "Hostname/IP" is not translated to russian in admin/words.js. You can use https://translator.iobroker.in/ for translations
- [ ] [E300] Not found on travis. Please setup travis
- [ ] [E605] No actual year found in copyright. Please add "Copyright (c) 2017-2022 AlCalzone <d.griesel@gmx.net>" at the end of README.md

I have also found warnings that may be fixed if possible.

- [ ] [W400] Cannot find "philips-tv" in latest repository

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by AlCalzone** [comment]
E605 fixed by de0d83b
W113, E115 fixed by #16 
E201 fixed

**Comment by ioBrokerChecker** [comment]
Do you need help fixing the bugs?
