### ISSUE TITLE
Recieving Http 401

### ISSUE THREAD

**Issue by alexpthe1** [AlCalzone/ioBroker.philips-tv#187]
Hi,

first of all thanks for your work wich i rly appreciate.
I installed the version for v6 API and paired my tv corrctly. But i alway recieve:

(17139) Error handling state change philips-tv.0.pressKey => Options: 401 - "<html>\n<head>\n <title>Status page</title>\n</head>\n<body style=\"font-family: sans-serif;\">\n<p style=\"font-size: 1
--

after trying to send a "key".
Hope you can invesigate in this problem (maybe i have done something wrong)

**Comment by AlCalzone** [comment]
Is there any way you can get the complete message? Its most likely in the downloadable log file.

**Comment by alexpthe1** [comment]
of course:

2020-02-19 23:45:40.211 - error: philips-tv.0 (17139) Error handling state change philips-tv.0.pressKey => WatchTV: 401 - "\n\n \n\n\n
Unauthorized

\n
The request requires user authentication

\n
You can get technical details here.
\nPlease continue your visit at our home page.\n

\n\n\n"

**Comment by alexpthe1** [comment]
http://192.168.178.41:1925/6/system

{"notifyChange":"http","menulanguage":"German","name":"65PUS7803\/12","country":"Germany","serialnumber_encrypted":"TvhWxwk4YRkekZBgKWoAE+dt4aLFOT+3XjXUw8PHc7A=\n","softwareversion_encrypted":"Lk4N5QZnyKrGEyNCICqX5xNZrecB9mqMM1TagnjmCe0cPNRaoFwnY4uYjZiI\/qQF\n","model_encrypted":"vzurGPiPiq3aKZgxUpktf\/HYauf3jPUr4+yP+2oTHok=\n","deviceid_encrypted":"9\/X7Vu1bK2ZBI5uoP6O5KI5HDauczl27rX0qbiW5LrQ=\n","nettvversion":"8.0.2","epgsource":"one","api_version":{"Major":6,"Minor":1,"Patch":0},"featuring":{"jsonfeatures":{"editfavorites":["TVChannels","SatChannels"],"recordings":["List","Schedule","Manage"],"ambilight":["LoungeLight","Hue","Ambilight"],"menuitems":["Setup_Menu"],"textentry":["context_based","initial_string_available","editor_info_available"],"applications":["TV_Apps","TV_Games","TV_Settings"],"pointer":["not_available"],"inputkey":["key"],"activities":["intent"],"channels":["preset_string"],"mappings":["server_mapping"]},"systemfeatures":{"tvtype":"consumer","content":["dmr","pvr"],"tvsearch":"intent","pairing_type":"digest_auth_pairing","secured_transport":"true","companion_screen":"true"}},"os_type":"MSAF_2018_O"}

**Comment by alexpthe1** [comment]
Here a screeshot of the objects
https://imgur.com/a/2wolHYB

**Comment by AlCalzone** [comment]
> The request requires user authentication

Seems the pairing was not successful or you haven't correctly updated the adapter configuration.

**Comment by alexpthe1** [comment]
Thanks i finaly get it working. Yep the Pairing was not sucessfull. I Finaly identitfyd a python script fooled me
