### ISSUE TITLE
Link List :-)

### ISSUE THREAD

**Issue by Apollon77** [AlCalzone/ioBroker.philips-tv#199]
* Wiki info: https://github.com/eslavnov/Pylips/wiki
* Shell Script: https://github.com/arzzen/philips-tv/blob/master/tv.sh
* Python/MQTT: https://github.com/b2un0/pylips
* Python/HASS: https://github.com/nstrelow/ha_philips_android_tv/blob/master/custom_components/philips_android_tv/media_player.py

**Comment by foxriver76** [comment]
Now there is also a node.js module https://github.com/konradknitter/philipsandroidtv which is also used by a homebridge plugin.

**Comment by foxriver76** [comment]
I am working on a new adapter which is based on the linked library: https://github.com/foxriver76/philips-tv-android

**Comment by AlCalzone** [comment]
Do you know if that works with the old non android ones, using the jointspace API? I'd guess not

**Comment by foxriver76** [comment]
I don't think it will work, the  and I am not familiar with the older API as I have a fairly new device. Lets say if the port of the API is different from 1926 it will not work for sure.

There is a homebridge plugin which uses this library and is only tested with 6.x API.
