### ISSUE TITLE
Could not poll API: read ECONNRESET

### ISSUE THREAD

**Issue by WernerRH21** [AlCalzone/ioBroker.philips-tv#440]
Ab und an bekomme ich im log im ioBroker folgende Fehlermeldung:

error | Could not poll API: read ECONNRESET

Ich verwende einen OLED806

iobroker Admin: v6.3.5
Nodejs: v16.19.1

**Comment by foxriver76** [comment]
Wenn er sich gleich wieder fängt all good, heißt nur dass eine einzelne Poll Anfrage nicht durch gekommen ist.

**Comment by WernerRH21** [comment]
Leider kommt es doch manchmal öfter in der Stunde vor. Dann gehen natürlich auch keine Kommandos. Poll Intervall einfach im Adapter hochsetzen?

**Comment by WernerRH21** [comment]
Vielleicht den Fehler gefunden. Hatte eine UniFi Viewport zur Kammeranzeige auf dem TV zwischengeschaltet und den TV somit LAN-mäßig nur weitergeleitet.
