### ISSUE TITLE
Update stable version in repo from 0.5.3 to 0.5.4

### ISSUE THREAD

**Issue by GermanBluefox** [AlCalzone/ioBroker.philips-tv#452]
# Think about update stable version to 0.5.4
**Version**: stable=**0.5.3** (533 days old) => latest=**0.5.4** (15 days old)
**Installs**: stable=**669** (82.59%), latest=**81** (10%), total=**810**

Click to use [developer portal](https://www.iobroker.dev/adapter/philips-tv/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1967)

**Do not close this issue manually as a new issue will be created if condition for update still exists.**

Please drop a comment if any reason exists which blocks updating to version 0.5.4 at this time.

Note: This is an automatically generated message and not personally authored by bluefox!
      @mcm1957 for evidence

**Comment by mcm1957** [comment]
Is there any reason to delay updating stable any longer?
Please drop a commit if you know any reason to refrain from updating.

**If there is no response until 07.09.2024 we could decide to update anyway.**

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 0.5.4 but the current stable version is already 0.5.4.

So this issue should be closed.

@mcm1957 for evidence
