### ISSUE TITLE
Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by andikarre** [AlCalzone/ioBroker.philips-tv#7]
Hallo AlCalzone,

erstmal großen Dank für den Philips TV Adapter. Nach sowas habe ich schon lange gesucht bzw. schon angefangen selber die API v6 meines TVs zu verstehen und anzusprechen. Hat auch geklappt  :geek: , aber dann bin ich über deinen Adapter gestolpert.

Das Pairing hatte ich bereits über die console durchgeführt und name und password dem Object hinzugefügt.

> const obj = getObject("system.adapter.philips-tv.0");
obj.native.username = "dein username hier";
obj.native.password = "dein passwort hier";
setObject("system.adapter.philips-tv.0", obj);

Der TV wird jetzt gefunden und der Adapter leuchtet grün.

Wenn ich aber PressKey ausführen möchte, bekomme ich folgende Fehlermeldung:
`error	Error handling state change philips-tv.0.pressKey => Standby: Cannot read property 'username' of undefined`

Scheint so, dass username und password hier nicht greifen.

Hast du eventuell auf Anhieb eine Lösung dafür? Ich habe die Version 0.3.0-alpha4

**Comment by andikarre** [comment]
Ich habe es inzwischen hinbekommen, in dem ich user und password manuell hinzugefügt habe.

`                    credentials = {
                        username: adapter.config.username || "",
                        password: adapter.config.password || "",
                    };`

Allerdings bekomme ich jetzt einen Timeout für Presskey:

`

philips-tv.0 | 2018-05-21 20:49:34.198 | error | Error handling state change philips-tv.0.pressKey => VolumeDown: Error: ESOCKETTIMEDOUT
-- | -- | -- | --
philips-tv.0 | 2018-05-21 20:49:29.143 | debug | state with id philips-tv.0.pressKey updated: ack=false; val=VolumeDown

`

**Comment by AlCalzone** [comment]
Hast du nach der Installation von Github ein Upload des Adapters durchgeführt? Wenn nicht, erklärt das die fehlende `username`-Eigenschaft.

Für das zweite Problem versuche ich heute Abend oder morgen eine Lösung zu finden. Reminder für mich:
> `agent: false, pool: {maxSockets: 100}`

**Comment by AlCalzone** [comment]
D.h. mit deinem obigen Skript funktioniert es auch nicht? Kann leider nicht selbst testen, da ich keinen v6-Fernseher habe.

**Comment by andikarre** [comment]
Nein. Sowohl GET als auch POST führt zum Timeout.
Seltsamerweise liefert dein Test mit GET audio/volume eine Response. Wieso ist das so? Bzw. hast du eine Idee an welchen Parametern, außer maxSockets, man noch schrauben könnte?

**Comment by AlCalzone** [comment]
Kannst du probeweise den `GET audio/volume` mehrfach schnell hintereinander abfragen? Eventuell geht es dem Fernseher zu schnell und er verweigert die Antwort. Dann müsste der Adapter die Anfragen throttlen, um Probleme zu vermeiden.

**Comment by andikarre** [comment]
Ok, jetzt kriege ich eine Response. Ich habe ein wenig mit maxSocket und der Anzahl der Abfragen romprobiert und konnte folgendes Verhalten feststellen:
bei maxSocket=1 bekomme ich ab 3 Abfragen eine Response.
bei maxSocket=10 bekomme ich ab 12 Abfrage eine Response.
--> je höher maxSocket eingestellt ist, desto mehr Requests muss ich senden.

`var rp = require('request-promise');
var dataString = '{"key":"Standby"}';

var options = {
//    timeout: 3000, // don't wait forever
	rejectUnauthorized: false, // enable self-signed certs
	agent: false,
	pool: {
		maxSockets: 1,
	},
    resolveWithFullResponse: true,
    method: 'GET',
    uri: 'https://XXX.XXX.XXX.XX:1926/6/audio/volume',
    auth: {
			username: 'XYZ',
			password: 'XYZ',
			sendImmediately: false,
		},
	simple: true,
//	body: dataString,
};
 

for (i=1;i<3;i++)  {
rp(options)

//    .then(function (parsedBody) {
//        console.log(parsedBody)
//    })
    .then(function (response) {
        console.log("respnse " + response.body);
//      console.log("Body " + body);
        })
        
    .catch(function (err) {
        console.log(err)
    });
}`

**Comment by andikarre** [comment]
Wenn ich ein POST z.B. zum Einschalten schicke, flackert kurz das Bild. Wenn ich mehr Durchgänge einstelle, geht der TV aus und wieder ein.

**Comment by AlCalzone** [comment]
Ok, das bedeutet zumindest, dass automatisches Nochmal-Senden zum Erfolg führen sollte. Versuche ich die Tage mal einzubauen.

**Comment by AlCalzone** [comment]
@andikarre Es ist zwar schon eine Weile her, aber ich habe gerade mal automatisches Nochmal-Senden in den Adapter eingebaut. Würde mich freuen, wenn du testen könntest.

**Comment by andikarre** [comment]
Hallo, leider bekomme ich immer noch einen Timeout:


```
philips-tv.0 | 2018-07-10 21:55:18.105 | error | Error handling state change philips-tv.0.pressKey => Options: Error: ESOCKETTIMEDOUT
-- | -- | -- | --
philips-tv.0 | 2018-07-10 21:55:05.337 | error | Error handling state change philips-tv.0.pressKey => VolumeDown: Error: ESOCKETTIMEDOUT
philips-tv.0 | 2018-07-10 21:54:47.352 | error | Error handling state change philips-tv.0.pressKey => VolumeUp: Error: ESOCKETTIMEDOUT
```

**Comment by AlCalzone** [comment]
Habe mal etwas mehr Log-Outputs eingebaut. Bitte nochmals aktualisieren, den Adapter auf Loglevel Debug stellen (Instanzen/Expertenmodus) und den Output hier posten.

**Comment by AlCalzone** [comment]
Ich hab in der vorigen Version vergessen, die Zugangsdaten tatsächlich zu verwenden. Womöglich antwortet der TV deswegen nicht. Bitte auf alpha7 von Github updaten.

**Comment by andikarre** [comment]
Super, mit dem genannten Branch funktioniert es. Habe einiges ausprobiert und es klappt soweit.

Noch ein Hinweis:
Man könnte noch ein WakeOnLan einbauen. Im Standby ist der TV über die API nicht mehr erreichbar. Zum Einschalten verwende ich das hier:
```
var wol = require('wake_on_lan');
wol.wake(mac);
```
Damit wäre man komplett unabhängig von einer Ansteuerung über Infrarot.

**Comment by andikarre** [comment]
Ach ja, die Befehle greifen bereits beim 1. Versuch:

`

philips-tv.0 | 2018-07-23 20:44:05.808 | debug | getWithDigestAuth("audio/volume")
-- | -- | -- | --
philips-tv.0 | 2018-07-23 20:44:05.791 | debug | connection is ALIVE
philips-tv.0 | 2018-07-23 20:44:05.778 | debug | attempt 1 of 3
philips-tv.0 | 2018-07-23 20:44:05.776 | debug | checking if connection is alive
philips-tv.0 | 2018-07-23 20:43:55.760 | debug | state with id philips-tv.0.volume updated: ack=true; val=0
philips-tv.0 | 2018-07-23 20:43:55.742 | debug | state with id philips-tv.0.muted updated: ack=true; val=true
philips-tv.0 | 2018-07-23 20:43:55.674 | debug | attempt 1 of 3
philips-tv.0 | 2018-07-23 20:43:55.672 | debug | getWithDigestAuth("audio/volume")
philips-tv.0 | 2018-07-23 20:43:55.642 | debug | connection is ALIVE
philips-tv.0 | 2018-07-23 20:43:55.625 | debug | attempt 1 of 3
philips-tv.0 | 2018-07-23 20:43:55.624 | debug | checking if connection is alive
philips-tv.0 | 2018-07-23 20:43:48.000 | debug | attempt 1 of 3
philips-tv.0 | 2018-07-23 20:43:47.996 | debug | postJSONwithDigestAuth("input/key", {"key":"Mute"})
philips-tv.0 | 2018-07-23 20:43:47.992 | debug | state with id philips-tv.0.pressKey updated: ack=false; val=Mute

`
